# Change these first
owner: ViewSonicCloud # Your GitHub organization or username, where this repository lives
repo: myViewBoard-Upptime # The name of this repository

sites:
  - name: myViewBoard Wiki
    url: https://wiki.myviewboard.com
  - name: myviewboard.com
    url: https://myviewboard.com
  - name: myViewBoard Web Service
    url: https://api.myviewboard.com

status-website:
  publish: true
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.myviewboard.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ViewSonicCloud/myViewBoard-Upptime/master/assets/icon.svg
  name: myViewBoard Cloud Service Uptime
  introTitle: "myViewBoard Web Service Status."
  introMessage: public availability for myviewboard.com
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
